# Numpy library

NumPy is a Python library.

NumPy is used for working with arrays.

NumPy is short for "Numerical Python".

In [1]:
# importing numpy library
import numpy as np

In [2]:
arr = np.array([1, 2, 3, 4, 5])

In [3]:
print(arr)

[1 2 3 4 5]


In [4]:
print(type(arr))

<class 'numpy.ndarray'>


In [5]:
# checking version
print(np.__version__)

1.20.3


In [6]:
# zero dimension array
arr = np.array(43)

In [7]:
print(arr)

43


In [8]:
print(arr.ndim)

0


In [9]:
#2 - D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

In [10]:
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
print(arr.ndim)

2


In [12]:
# 3 - D array
arr = np.array([[[1, 2, 3],[4, 5, 6], [7, 8, 9]]])

In [13]:
print(arr)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [14]:
print(arr.ndim)

3


In [15]:
# higher dimensional arrays
arr = np.array([1, 2, 3, 4], ndmin = 5)

In [16]:
print(arr)

[[[[[1 2 3 4]]]]]


In [17]:
print(arr.ndim)

5


In [18]:
#Access Array Elements
arr = np.array([1, 2, 3, 4])

In [19]:
print(arr[0])

1


In [20]:
# access 2 - D arrays
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [21]:
print("2nd element on 1st row: ", arr[0, 1])

2nd element on 1st row:  2


In [22]:
arr[1, 3]

9

In [23]:
# access 3 - D arrays
arr = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]]])

In [24]:
arr[0, 1, 2]

6

In [25]:
# Numpy array slicing
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [26]:
print(arr[4:])

[5 6 7]


In [27]:
print(arr[:4])

[1 2 3 4]


In [28]:
# negative slicing
print(arr[-3:-1])

[5 6]


STEP : 
    
Use the step value to determine the step of the slicing

In [29]:
print(arr)

[1 2 3 4 5 6 7]


In [30]:
print(arr[1:5:2])

[2 4]


In [31]:
arr[::2]

array([1, 3, 5, 7])

In [32]:
# Slicing 2_D array
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

In [33]:
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [34]:
print(arr[1, 1:4])

[7 8 9]


In [35]:
print(arr[0:2, 2])

[3 8]


In [36]:
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


data types numpy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

i - integer

b - boolean

u - unsigned integer

f - float

c - complex float

m - timedelta

M - datetime

O - object

S - string

U - unicode string

V - fixed chunk of memory for other type ( void )

In [37]:
#checking the data type of an array

The NumPy array object has a property called dtype that returns the data type of the array


In [38]:
arr = np.array([1, 2, 3, 4])

In [39]:
print(arr)

[1 2 3 4]


In [40]:
print(arr.dtype)

int32


In [41]:
arr1 = np.array(['apple', 'banana', 'cherry'])

print(arr1.dtype)

<U6


In [42]:
# creating arrays with a defined data type
arr2 = np.array([1, 2, 3, 4], dtype='S')

print(arr2)
print(arr2.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [43]:
#For i, u, f, S and U we can define size as well.
arr3 = np.array([1, 2, 3, 4], dtype='i4')

print(arr3)
print(arr3.dtype)

[1 2 3 4]
int32


In [44]:
# shape of an array

In [45]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [46]:
arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


In [47]:
# numpy array reshaping

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

In [48]:
# reshape from 1-D to 2-D
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [49]:
# transposing array
newarr.transpose()

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [50]:
newarr.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [51]:
# reshape from 1-D to 3-D
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr1 = arr1.reshape(2, 3, 2)

print(newarr1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [52]:
newarr1.transpose()

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

In [53]:
newarr1.T

array([[[ 1,  7],
        [ 3,  9],
        [ 5, 11]],

       [[ 2,  8],
        [ 4, 10],
        [ 6, 12]]])

In [54]:
# for reverse the array
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [55]:
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [56]:
reversed_arr = np.flip(arr_2d)

In [57]:
print(reversed_arr)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [58]:
# Numpy array iterating


Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [59]:
# iterrating 1-D array
arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


In [60]:
#iterating 2-D array
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr1:
    print(x)

[1 2 3]
[4 5 6]


In [61]:
for x in arr:
    for y in x:
        print(y)

TypeError: 'numpy.int32' object is not iterable

In [ ]:
#iterating 3-D array
arr3 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr3:
    print(x)

In [ ]:
for x in arr3:
    for y in x:
        for z in y:
            print(z)

In [ ]:
# joining numpy arrays


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)

In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

In [62]:
# joining array with stack function
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis = 1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [63]:
# stacking along rows
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [64]:
# stacking along columns
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


#numpy spliting array : splitting is reverese operation of joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.


In [65]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [66]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [67]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [68]:
# splitting 2-D array
arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [69]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [70]:
#numpy searching arrays : To search an array, use the where() method.
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)

(array([3, 5, 6], dtype=int64),)


In [71]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7], dtype=int64),)


Search sorted : There is a method called searchsorted() which performs a binary search in the array, and returns the index where the specified value would be inserted to maintain the search order.

In [72]:
arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


In [73]:
#numpy sorting arrays
arr = np.array([3, 2, 0, 1])
print(np.sort(arr))

[0 1 2 3]


In [74]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [75]:
#sorting 2-D arrays
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


In [76]:
# filtering arrays
arr = np.array([42, 41, 14, 46, 47, 25, 49])
# create an empty list
filter_arr = []
# go through each element in arr
for element in arr:
    # if the element is higher than 42, set the value to True, otherwise false;
    if element > 42:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False, False, False, True, True, False, True]
[46 47 49]


In [77]:
#Create a filter array that will return only even elements from the original array:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is completely divisble by 2, set the value to True, otherwise False
    if element % 2 == 0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False, True, False, True, False, True, False]
[2 4 6]


In [78]:
#Creating Filter Directly From Array
arr = np.array([41, 42, 43, 44])

filter_arr = arr > 42

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [79]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

filter_arr = arr % 2 == 0

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]


# Simple Arithmetic

In [80]:
arr1 = np.array([10, 11, 12, 13, 14, 15, 16])
arr2 = np.array([20, 21, 22, 23, 24, 25, 26])


In [81]:
print(arr1)
print(arr2)

[10 11 12 13 14 15 16]
[20 21 22 23 24 25 26]


In [82]:
# addition
newarr = np.add(arr1, arr2)
print(newarr)


[30 32 34 36 38 40 42]


In [83]:
# subtraction
new1 = np.subtract(arr1, arr2)
print(new1)

[-10 -10 -10 -10 -10 -10 -10]


In [84]:
# multiplication
new2 = np.multiply(arr1, arr2)
print(new2)

[200 231 264 299 336 375 416]


In [85]:
# Division
new3 = np.divide(arr1, arr2)
print(new3)

[0.5        0.52380952 0.54545455 0.56521739 0.58333333 0.6
 0.61538462]


In [86]:
# power
new4 = np.power(arr1, arr2)
print(new4)

[ 1661992960   602408795           0  1487897765  1090519040 -1144744561
           0]


In [87]:
# remainder
new5 = np.mod(arr1, arr2)
print(new5)

[10 11 12 13 14 15 16]


In [88]:
newarr6 = np.remainder(arr1, arr2)
print(newarr6)

[10 11 12 13 14 15 16]


In [89]:
# Quotient and mod
new7 = np.divmod(arr1, arr2)
print(new7)

(array([0, 0, 0, 0, 0, 0, 0], dtype=int32), array([10, 11, 12, 13, 14, 15, 16], dtype=int32))


In [90]:
# Absolute values
arr = np.array([-1, -2, 1, 2, 3, -4])
new8 = np.absolute(arr)
print(new8)

[1 2 1 2 3 4]


In [91]:
arr = np.array([10, 11, 12, 13, 14, 15, 16])
print(arr)

[10 11 12 13 14 15 16]


In [92]:
arr.max()

16

In [93]:
arr.min()

10

In [94]:
arr.sum()

91

In [95]:
# Creating matrices
a = np.ones((4, 3, 2))

In [96]:
print(a)

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [97]:
b = np.zeros((3, 2, 2))

In [98]:
print(b)

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]


In [99]:
# numpy logs
# log at base 2
arr = np.arange(1, 10)
print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [100]:
# log at base 10
arr = np.arange(1, 10)
print(np.log10(arr))

[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.84509804 0.90308999 0.95424251]


In [101]:
# log at base e
arr = np.arange(1, 10)
print(np.log(arr))

[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458]
